import "../App.css";
import React from "react";
import { useState } from "react";
import NFTs from "../images/NFTs.gif";
import showcase from "../images/showcase.png";
import alien21 from "../images/gang/alien21.png";
import alien32 from "../images/gang/alien32.png";
import alien35 from "../images/gang/alien35.png";
import alien73 from "../images/gang/alien73.png";

import Cyan from "../images/layers/Backgrounds/Cyan.png";
import Mustard from "../images/layers/Backgrounds/Mustard.png";
import Orange from "../images/layers/Backgrounds/Orange.png";
import Pink from "../images/layers/Backgrounds/Pink.png";
import Purple from "../images/layers/Backgrounds/Purple.png";
import Red from "../images/layers/Backgrounds/Red.png";
import Yellow from "../images/layers/Backgrounds/Yellow.png";
import Black from "../images/layers/Backgrounds/Black.png";
import Grey from "../images/layers/Backgrounds/Grey.png";
import Transparent from "../images/layers/Backgrounds/Transparent.png";

import Camo from "../images/layers/Body/Camo.png";
import Coat from "../images/layers/Body/Coat.png";
import Hoodie from "../images/layers/Body/Hoodie.png";
import OpenShirt from "../images/layers/Body/OpenShirt.png";
import WhiteCollarShirt from "../images/layers/Body/WhiteCollarShirt.png";
import Windbreaker from "../images/layers/Body/Windbreaker.png";
import ZipUp from "../images/layers/Body/ZipUp.png";

import BlueFace from "../images/layers/Face/BlueFace.png";
import BlueishFace from "../images/layers/Face/BlueishFace.png";
import GreenFace from "../images/layers/Face/GreenFace.png";
import PurpleFace from "../images/layers/Face/PurpleFace.png";
import RedFace from "../images/layers/Face/RedFace.png";
import SalmonFace from "../images/layers/Face/SalmonFace.png";
import YellowFace from "../images/layers/Face/YellowFace.png";

import Beanie from "../images/layers/Hats/Beanie.png";
import BucketHat from "../images/layers/Hats/BucketHat.png";
import Cap from "../images/layers/Hats/Cap.png";
import FivePanel from "../images/layers/Hats/FivePanel.png";
import Helmet from "../images/layers/Hats/Helmet.png";
import SkiMask from "../images/layers/Hats/SkiMask.png";
import Sombrero from "../images/layers/Hats/Sombrero.png";

import Background from "./Customize/Background";

const Hero = () => {
  const [background, setBackground] = useState(Black);
  const [body, setBody] = useState(Transparent);
  const [face, setFace] = useState(Transparent);
  const [clothes, setClothes] = useState(Transparent);
  const [hat, setHat] = useState(Transparent);

  const backgrounds = [Cyan, Mustard, Orange, Pink, Purple, Red, Yellow, Black, Transparent]
  const faces = [BlueFace, BlueishFace, GreenFace, PurpleFace, RedFace, SalmonFace, YellowFace]
  const clothing = [Camo, Coat, Hoodie, OpenShirt, WhiteCollarShirt, Windbreaker, ZipUp]
  const hats = [Beanie, BucketHat, Cap, FivePanel, Helmet, SkiMask, Sombrero]

  return (
    <>
      {/* customize section */}
      <section id="specs">
        <div className="container py-5 px-10 space-y-5">
          <h1 className="text-3xl text-center mt-5 text-white font-mono font-bold italic md:text-left">
            SPECS
          </h1>
          <p className="md:w-2/3 text-white text-justify">
            Each Gang Member is designed and generated by more than 30 different traits.
            These traits include: caps, clothes, eyes, colors, backgrounds, and more. Any combination is cool, but some are cooler than others. Check out all of the available combinantions below!
          </p>
        </div>
        <div className="container flex flex-col-reverse items-start mx-auto p-10 pt-0 bg-bgBlack md:flex-row md:mb-10 md:pt-10">
          {/* left item */}
          <div className="flex flex-col mt-8 space-y-3 md:w-1/3 md:mt-0 md:space-y-5">
            {/* <Background /> */}
            <div className="flex flex-col">
              <div>
                <p className="max-w-xl text-white font-bold md:text-lg">Background:</p>
              </div>
              <div className="flex flex-wrap justify-start space-y-3 max-w-sm">
              {backgrounds.map((img, idx) => (
                <img
                  src={img}
                  alt="Gang Member"
                  className="rounded-lg mt-3 mr-3 w-14 h-14 hover:scale-110 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setBackground(img)}
                  key={idx}
                />
                ))}
                </div>
            </div>
            {/* Eye Color */}
            <div className="flex flex-col">
              <div>
                <p className="max-w-xl text-white font-bold md:text-lg">Face:</p>
              </div>
              <div className="flex flex-wrap justify-start space-y-3 max-w-sm">
              {faces.map((img, idx) => (
                <img
                  src={img}
                  alt="Gang Member"
                  className="rounded-md mt-3 mr-3 w-14 h-14 bg-black hover:scale-110 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setFace(img)}
                  key={idx}
                />
                ))}
                </div>
            </div>
          </div>
          {/* center item */}
          <div className="flex flex-col mt-8 space-y-3 md:w-1/3 md:mt-0 md:space-y-5  ">
            {/* Eye Color */}
            {/* <div className="flex flex-col">
              <div>
                <p className="max-w-xl text-white md:text-lg">Body Color:</p>
              </div>
              <div className="flex space-x-3 mt-3 ">
                <img
                  src={alien35}
                  alt="Gang Member"
                  className="rounded-md w-14 h-14 hover:scale-110 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setBody(alien35)}
                />
                <img
                  src={alien32}
                  alt="Gang Member"
                  className="rounded-md w-14 h-14 hover:scale-110 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setBody(alien32)}
                />
                <img
                  src={alien73}
                  alt="Gang Member"
                  className="rounded-md w-14 h-14 hover:scale-110 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setBody(alien73)}
                />
                <img
                  src={alien35}
                  alt="Gang Member"
                  className="rounded-md w-14 h-14 hover:scale-110 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setBody(alien35)}
                />
                <img
                  src={alien32}
                  alt="Gang Member"
                  className="rounded-md w-14 h-14 hover:scale-110 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setBody(alien21)}
                />
              </div>
            </div> */}
            {/* Body Clothes */}
            <div className="flex flex-col">
              <div>
                <p className="text-white font-bold md:text-lg">Clothes:</p>
              </div>
              <div className="flex flex-wrap justify-start space-y-3 max-w-sm">
              {clothing.map((img, idx) => (
                <img
                  src={img}
                  alt="Gang Member"
                  className="rounded-md mt-3 mr-3 w-14 h-14 bg-black hover:scale-95 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setClothes(img)}
                  key={idx}
                />
                ))}
                </div>
             
            </div>
            {/* Hat */}
            <div className="flex flex-col">
              <div>
                <p className="text-white font-bold md:text-lg">Hat:</p>
              </div>
              <div className="flex flex-wrap justify-start space-y-3 max-w-sm">
              {hats.map((img, idx) => (
                <img
                  src={img}
                  alt="Gang Member"
                  className="rounded-md mt-3 mr-3 w-14 h-14 bg-black hover:scale-95 hover:shadow-md hover:shadow-slate-600 hover:cursor-pointer"
                  onClick={() => setHat(img)}
                  key={idx}
                />
                ))}
                </div>
            </div>
          </div>
          {/* right item (Changing Item) */}
          <div className="flex w-full relative md:w-1/3">
            {/* background */}
            <img
              src={background}
              alt="Background"
              className="rounded-md relative md:w-80 md:ml-auto z-1"
            />
            {/* body */}
            {/* <img
              src={body}
              alt="Body"
              className="rounded absolute inset-0 md:w-80 md:ml-auto z-2"
            /> */}
            {/* face */}
            <img
              src={face}
              alt="Face"
              className="rounded absolute inset-0 md:w-80 md:ml-auto z-3"
            />
            {/* clothes */}
            <img
              src={clothes}
              alt="Clothes"
              className="rounded absolute inset-0 md:w-80 md:ml-auto z-4"
            />
            {/* cap */}
            <img
              src={hat}
              alt="Hat"
              className="rounded absolute inset-0 md:w-80 md:ml-auto z-5"
            />
          </div>
        </div>
      </section>
    </>
  );
};

export default Hero;
